<?php
/**
 * Created by PhpStorm.
 * User:jiayongwei
 * Date: 2017/11/29
 * Time: 14:32
 */
namespace app\index\controller;
use think\Db;
class Base extends \app\common\controller\Base
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
}